# This is a basic workflow to help you get started with Actions

name: Compile buildroot for Beagle Board

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Update Runner
        run: sudo apt-get update && sudo apt-get upgrade -y --no-install-recommends

      - name: Install Dependencies
        run: |
          sudo apt-get install -y --no-install-recommends \
          build-essential \
          cpio \
          bc \
          sed \
          make \
          binutils \
          diffutils \
          gcc \
          g++ \
          bash \
          patch \
          gzip \
          bzip2 \
          perl \
          tar \
          unzip \
          rsync \
          file \
          findutils \
          wget

      - name: Copy .config into buildroot
        run: cp .config buildroot/

      # Runs a set of commands using the runners shell
      - name: Compile .config for Beagle Board
        working-directory: buildroot
        run: make

      - name: List Output Directory
        working-directory: buildroot
        run: ls -l output/

      - name: List Images Directory
        working-directory: buildroot
        run: ls -l output/images

      # List outputs
      - name: Upload Beagle Board Artifact
        uses: actions/upload-artifact@v4
        with:
          name: beagle-board-buildroot-2023.02.11-modified
          path: ./buildroot/output/images
