# This is a basic workflow to help you get started with Actions

name: Compile buildroot for Beagle Board

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      BUILDROOT_VERSION: 2024.11

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Update Runner
        run: sudo apt-get update && sudo apt-get upgrade -y --no-install-recommends

      - name: Install Dependencies
        run: |
          sudo apt-get install -y --no-install-recommends \
          build-essential \
          cpio \
          bc \
          sed \
          make \
          binutils \
          diffutils \
          gcc \
          g++ \
          bash \
          patch \
          gzip \
          bzip2 \
          perl \
          tar \
          unzip \
          rsync \
          file \
          findutils \
          wget

      # Download Artifact from buildroot.org
      - name: Download Artifact from buildroot.org
        run: wget https://gitlab.com/buildroot.org/buildroot/-/archive/${{env.BUILDROOT_VERSION}}/buildroot-${{env.BUILDROOT_VERSION}}.tar.gz

      - name: Extract Artifact
        run: tar -xvf buildroot-${{env.BUILDROOT_VERSION}}.tar.gz
      
      # Runs a single command using the runners shell
      - name: Generate .config for Beagle Board
        working-directory: ./buildroot-${{env.BUILDROOT_VERSION}}
        run: make beaglebone_defconfig

      # Runs a set of commands using the runners shell
      - name: Compile .config for Beagle Board
        working-directory: ./buildroot-${{env.BUILDROOT_VERSION}}
        run: make

      - name: List Output Directory
        run: ls -l output/

      - name: List Images Directory
        run: ls -l output/images

      # List outputs
      - name: Upload Beagle Board Artifact
        uses: actions/upload-artifact@v4
        with:
          name: beagle-board-buildroot-${{ env.BUILDROOT_VERSION }}
          path: output/images
